# Generated by Django 5.1.15 on 2026-08-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellness", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mood",
            name="feeling_tags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="mood",
            name="mood_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
