# @author Bodo Desderio <rooiboktechltd@gmail.com>
# @copyright 2026 Rooibok Technologies. All rights reserved.
# Generated by Django 5.1.15 on 2026-08-01 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("event_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("organizer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "events",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("article", "Article"),
                            ("music", "Music"),
                            ("audio", "Audio"),
                            ("podcast", "Podcast"),
                            ("routine", "Routine"),
                            ("video", "Video"),
                            ("image", "Image"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_url", models.CharField(max_length=500)),
                (
                    "preview_image_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("downloads", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0)),
                (
                    "consultant",
                    models.ForeignKey(
                        db_column="consultant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resources",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        db_column="recipient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "indexes": [
                    models.Index(
                        fields=["recipient"], name="notifications_recipient_id_idx"
                    )
                ],
            },
        ),
    ]
