# Generated by Django 5.1.15 on 2026-08-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="streak_days",
            field=models.IntegerField(default=0),
        ),
    ]
