# Generated by Django 5.1.15 on 2026-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_streak_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultantdetails",
            name="currency",
            field=models.CharField(default="UGX", max_length=3),
        ),
        migrations.AddField(
            model_name="consultantdetails",
            name="session_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
