# Generated by Django 5.1.15 on 2026-08-01 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subjective", models.TextField(blank=True, default="")),
                ("objective", models.TextField(blank=True, default="")),
                ("assessment", models.TextField(blank=True, default="")),
                ("plan", models.TextField(blank=True, default="")),
                ("shared_with_client", models.BooleanField(default=False)),
                (
                    "appointment",
                    models.OneToOneField(
                        db_column="appointment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_note",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        db_column="consultant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session_notes",
            },
        ),
    ]
